MAX_COLOR_LENGHT = 7
MAX_EMAIL_LENGTH = 254
MAX_FIELD_LENGTH = 256
MAX_FIRST_NAME_LENGTH = 150
MAX_INGREDIENT_NAME_LENGTH = 128
MAX_LAST_NAME_LENGTH = 150
MAX_MEASUREMENT_LENGTH = 64
MAX_PASSWORD_LENGTH = 150
MAX_TAG_LENGTH = 32
MAX_USERNAME_LENGTH = 150

AMOUNT_MAX = 10000
AMOUNT_MIN = 1
MAX_COOKING_TIME = 32000
MIN_COOKING_TIME = 1

REGULAR_CHECK_LOGIN_VALID = r'^[\w. @ +-]+\Z'

PAGE_SIZE = 6
